# fly.toml app configuration file generated for ppp-api on 2024-04-07T10:33:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ppp-api'
primary_region = 'fra'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
  MESSAGE = 'Hello from Fly!'

[metrics]
  port = 8080
  path = "/actuator/prometheus"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
