spring:
  application:
    name: ppp-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
    password: ${SUPABASE_PPP_API_PASSWORD}
    username: postgres.xdlzubousuiqlqbrggeb
  jpa:
    open-in-view: false
  docker:
    compose:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  endpoint:
    flyway:
      enabled: false
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        step: 1m
        descriptions: false
server:
  forward-headers-strategy: framework
app:
  open-exchange-rates-api-key: ${OPEN_EXCHANGE_RATES_API_KEY:notset}
  open-exchange-rates-api-id: ${OPEN_EXCHANGE_RATES_API_KEY:notset}
  quandl-api-key: ${QUANDL_API_KEY:notset}
