spring:
  r2dbc:
    url: r2dbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
    password: ${SUPABASE_PPP_API_PASSWORD}
    username: postgres.xdlzubousuiqlqbrggeb
  jooq:
    sql-dialect: postgres
  application:
    name: ppp-api
  docker:
    compose:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
  security:
    user:
      password: changeme
  flyway:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  endpoint:
    flyway:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        step: 1m
        descriptions: false
server:
  forward-headers-strategy: framework
app:
  open-exchange-rates-api-key: ${OPEN_EXCHANGE_RATES_API_KEY:notset}
  open-exchange-rates-api-id: ${OPEN_EXCHANGE_RATES_API_KEY:notset}
  quandl-api-key: ${QUANDL_API_KEY:notset}
