name: Deploy Application
on:
  push:
  schedule:
    - cron: '0 15 * * *' # daily at 3pm

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

jobs:
  build-and-test:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    name: Build Application
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.5.4

      - name: Set Now
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build & publish app
        env:
          SUPABASE_PPP_API_PASSWORD: ${{ secrets.SUPABASE_PPP_API_PASSWORD }}
          RELEASE_TAG: "${{ env.NOW }}-${{ github.run_id }}"
        run: |
          pack build ghcr.io/rieckpil/purchasing-power-parity-api:${{ env.RELEASE_TAG }} \
              --builder paketobuildpacks/builder-jammy-base \
              --path . \
              --env "MAVEN_OPTS=-Dorg.jooq.no-logo=true -Dorg.jooq.no-tips=true" \
              --env "SUPABASE_PPP_API_PASSWORD" \
              --env "BP_OCI_SOURCE=https://github.com/rieckpil/purchasing-power-parity-api" \
              --env "BP_JVM_VERSION=21" \
              --publish

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        run: flyctl deploy --image ghcr.io/rieckpil/purchasing-power-parity-api:${{ env.RELEASE_TAG }}
        env:
          RELEASE_TAG: "${{ env.NOW }}-${{ github.run_id }}"
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
