name: Deploy Application
on:
  push:
  schedule:
    - cron: '0 15 * * *' # daily at 3pm

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

jobs:
  build-and-test:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    name: Build Application
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.5.4

      - name: Setup for JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          java-package: jdk
          cache: maven

      - name: Build & publish app
        run: |
          pack build ghcr.io/rieckpil/purchasing-power-parity-api:latest \
              --builder paketobuildpacks/builder-jammy-base \
              --path . \
              --env "MAVEN_OPTS=-Xms256m -Xmx512m" \
              --env "BP_LOG_LEVEL=DEBUG" \
              --env "BP_OCI_SOURCE=https://github.com/rieckpil/purchasing-power-parity-api" \
              --env "BP_JVM_VERSION=21" \
              --network=host \
              --docker-host=inherit \
              --publish

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        run: flyctl deploy --image ghcr.io/rieckpil/rieckpil/purchasing-power-parity-api:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
